// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcw9imY_yRqdBS3eFMNaYwb2mCdf3RM8',
    appId: '1:11037038153:web:77d8ab97a96f4305589198',
    messagingSenderId: '11037038153',
    projectId: 'ootd-4c7b4',
    authDomain: 'ootd-4c7b4.firebaseapp.com',
    storageBucket: 'ootd-4c7b4.firebasestorage.app',
    measurementId: 'G-XM0EWB389E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgOq_9m9Hp8j6DVhCWIuM4MEIwy3a4lIU',
    appId: '1:11037038153:android:0b46ab1344f7a611589198',
    messagingSenderId: '11037038153',
    projectId: 'ootd-4c7b4',
    storageBucket: 'ootd-4c7b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTem2IUjUoqf5FbsmCbW1Jhm8943E5U24',
    appId: '1:11037038153:ios:ae80f63ba3a6fe13589198',
    messagingSenderId: '11037038153',
    projectId: 'ootd-4c7b4',
    storageBucket: 'ootd-4c7b4.firebasestorage.app',
    iosBundleId: 'com.example.wordAnalyzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTem2IUjUoqf5FbsmCbW1Jhm8943E5U24',
    appId: '1:11037038153:ios:ae80f63ba3a6fe13589198',
    messagingSenderId: '11037038153',
    projectId: 'ootd-4c7b4',
    storageBucket: 'ootd-4c7b4.firebasestorage.app',
    iosBundleId: 'com.example.wordAnalyzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJcw9imY_yRqdBS3eFMNaYwb2mCdf3RM8',
    appId: '1:11037038153:web:10f5402724d8d266589198',
    messagingSenderId: '11037038153',
    projectId: 'ootd-4c7b4',
    authDomain: 'ootd-4c7b4.firebaseapp.com',
    storageBucket: 'ootd-4c7b4.firebasestorage.app',
    measurementId: 'G-FFKFM10V41',
  );
}
