name: ootd
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_storage: ^12.4.2
  cloud_firestore: ^5.6.3


  url_launcher: ^6.0.9
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0 
  logger: ^2.5.0
  



  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/hanger.png
    - assets/tops/
    - assets/bottoms/
    - assets/shoes/

fonts:
   - family: Italiana
     fonts:
       - asset: assets/fonts/Italiana-Regular.ttf
   - family: Prata
     fonts:
       - asset: assets/fonts/Prata-Regular.ttf
   - family: Cormorant
     fonts:
       - asset: assets/fonts/CormorantGaramond-Bold.ttf


